{% set name = "ansys-mapdl-reader" %}
{% set version = "0.54.1" %}

package:
  name: ansys-mapdl-reader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e9ae69f8c674e111ed46628f55296c25ef4ec1ec603eda9edb39bc49895dfe13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - appdirs >=1.4.0
    - matplotlib-base >=3.0.0
    - tqdm >=4.45.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ansys.mapdl.reader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyansys/pymapdl-reader
  summary: Legacy binary interface to MAPDL binary files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
