{% set name = "ansys-mapdl-reader" %}
{% set version = "0.52.6" %}

package:
  name: ansys-mapdl-reader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansys-mapdl-reader-{{ version }}.tar.gz
  sha256: 14c19fc9733012c7f2b34067f18fb646a77cb7cae230459e2218cdfc292b62f1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - glew
  run:
    - python
    - pyvista >=0.23.0
    - appdirs >=1.4.0
    - matplotlib-base >=3.0.0
    - tqdm >=4.45.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ansys.mapdl.reader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyansys/pymapdl-reader
  summary: Legacy binary interface to MAPDL binary files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
